#!/usr/bin/env bash
# Run Nexus hooks related commands.

update_lsb_release() {
    sed -i /etc/lsb-release \
        -e 's|^DISTRIB_ID=.*$|DISTRIB_ID=nexus|' \
        -e 's|^DISTRIB_DESCRIPTION=.*$|DISTRIB_DESCRIPTION=\"Nexus Linux\"|'
}

update_os_release() {
    local os_release="/etc/os-release"
    sed -i "$os_release" \
        -e 's|^NAME=.*$|NAME=\"Nexus Linux\"|' \
        -e 's|^PRETTY_NAME=.*$|PRETTY_NAME=\"Nexus Linux\"|' \
        -e 's|^ID=.*$|ID=nexus|' \
        -e 's|^ID_LIKE=.*$|ID_LIKE=arch|' \
        -e 's|^ANSI_COLOR=.*$|ANSI_COLOR=\"38;2;23;147;209\"|' \
        -e 's|^HOME_URL=.*$|HOME_URL=\"https://nexuslinux.org/\"|' \
        -e 's|^DOCUMENTATION_URL=.*$|DOCUMENTATION_URL=\"https://wiki.nexuslinux.org/\"|' \
        -e 's|^SUPPORT_URL=.*$|SUPPORT_URL=\"https://forum.nexuslinux.org/\"|' \
        -e 's|^BUG_REPORT_URL=.*$|BUG_REPORT_URL=\"https://github.com/nexuslinux/\"|' \
        -e 's|^LOGO=.*$|LOGO=nexus|'

    # add missing ID_LIKE=
    if ! grep -q "^ID_LIKE=" "$os_release" && grep -q "^ID=" "$os_release"; then
        sed -i "$os_release" -e '/^ID=/a \ID_LIKE=arch'
    fi
}

update_issues() {
    sed -i 's|Arch Linux|Nexus Linux|g' /etc/issue /usr/share/factory/etc/issue
}

case "$1" in
    os-release) update_os_release ;;
    lsb-release) update_lsb_release ;;
    *)
        update_os_release
        update_lsb_release
        update_issues
        ;;
esac
