# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
dontChroot: false
timeout: 3600
script:
  - "-rm ${ROOT}/home/@@USER@@/.xinitrc"
  - "-rm ${ROOT}/home/@@USER@@/.bash_profile"
  - "-rm ${ROOT}/etc/sudoers.d/g_wheel"
  - "-rm -r ${ROOT}/etc/systemd/system/getty@tty1.service.d"
  - "-rm ${ROOT}/etc/systemd/system/etc-pacman.d-gnupg.mount"
  - "-rm ${ROOT}/root/{.automated_script.sh,.zlogin,.xinitrc,.xsession,.xprofile,.wget-hsts,.screenrc,.ICEauthority}"
  - "-rm ${ROOT}/root/.config/{qt5ct,Kvantum,dconf}"
  - "-rm ${ROOT}/etc/polkit-1/rules.d/49-nopasswd_global.rules"
  - "-rm ${ROOT}/etc/polkit-1/rules.d/49-nopasswd-calamares.rules"
  - "-rm ${ROOT}/etc/systemd/system/display-manager.service"
  - "-rm -r ${ROOT}/etc/sddm.conf.d"
  - "-mv ${ROOT}/etc/sddm{-bk,}.conf"
  - "-rm ${ROOT}/etc/motd"
  - "bash ${ROOT}/usr/share/nexus-calamares/write-os-release.sh"
  - command: "/usr/local/bin/dmcheck"
  - "-rm @@ROOT@@/usr/local/bin/dmcheck"
  - "-rm @@ROOT@@/usr/local/bin/calamares-offline.sh"
  - "-rm @@ROOT@@/usr/local/bin/calamares-online.sh"
  - "-rm @@ROOT@@/etc/skel/.xinitrc"
  - "-rm @@ROOT@@/etc/skel/.bash_profile"
  - '-runuser @@USER@@ -c "cp -rf @@ROOT@@/etc/skel/. @@ROOT@@/home/@@USER@@/."'
  - '-runuser @@USER@@ -c "rm -rf @@ROOT@@/home/@@USER@@/{.xsession,.xprofile,.xinitrc}"'
  - "sed -i 's|Server = file:///usr/share/nexus-repo/|Server = https://github.com/nexuslinux-os/NexusLinux/releases/latest/download/|' ${ROOT}/etc/pacman.conf"