title   Nexus Linux %ARCH% UEFI Zen
sort-key B
linux   /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-zen
initrd  /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-zen.img
options archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% cow_spacesize=10G copytoram=auto module_blacklist=pcspkr i915.modeset=1 amdgpu.modeset=1 nvme_load=yes
